Name: app
Host: 0.0.0.0
Port: 8888

UserRPC:
  Etcd:
    Hosts:
      - 121.5.231.228:2379
    Key: user.rpc

VideoRPC:
  Etcd:
    Hosts:
      - 121.5.231.228:2379
    Key: video.rpc

InteractionRPC:
  Etcd:
    Hosts:
      - 121.5.231.228:2379
    Key: interaction.rpc